/*-
 * Copyright (C) 2009 Erik Larsson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.catacombae.hfsexplorer.unfinished;

import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

import static org.jdesktop.layout.GroupLayout.BASELINE;
import static org.jdesktop.layout.GroupLayout.DEFAULT_SIZE;
import static org.jdesktop.layout.GroupLayout.LEADING;
import static org.jdesktop.layout.GroupLayout.PREFERRED_SIZE;
import static org.jdesktop.layout.GroupLayout.TRAILING;
import static org.jdesktop.layout.LayoutStyle.RELATED;


/**
 * @author <a href="https://catacombae.org" target="_top">Erik Larsson</a>
 */
public class WelcomePanel extends javax.swing.JPanel {

    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jList1 = new JList<>();
        jRadioButton1 = new JRadioButton();
        jLabel1 = new JLabel();
        jRadioButton2 = new JRadioButton();
        jTextField1 = new JTextField();
        jButton2 = new JButton();
        jButton3 = new JButton();

        jButton1.setText("Load");

        jList1.setModel(new AbstractListModel<>() {
            final String[] strings = {"Macintosh HD (\\\\?\\GLOBALROOT\\Device\\Harddisk0\\Partition2)", "Leopard HD (\\\\?\\GLOBALROOT\\Device\\Harddisk0\\Partition3)", "Snow Leopard HD (GPT:5@\\\\?\\GLOBALROOT\\Device\\Harddisk0\\Partition0)", "Time Machine-s�kerhetskopior (EBR:2@MBR:4@\\\\?\\GLOBALROOT\\Device\\Harddisk1\\Partition0)", "Mac OS X Install DVD (\\\\?\\GLOBALROOT\\Device\\CdRom0\\Partition0)", " ", "eller:", " ", "Macintosh HD (/dev/hda2)", "Leopard HD (/dev/hda3)", "Snow Leopard HD (GPT:5@/dev/hda)", "etc.", " "};

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Detected file systems");

        jLabel1.setText("Select a file system to load:");

        jRadioButton2.setText("From file");

        jButton2.setText("Browse...");

        jButton3.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(LEADING)
                                        .add(layout.createParallelGroup(LEADING)
                                                .add(layout.createSequentialGroup()
                                                        .add(29, 29, 29)
                                                        .add(jTextField1, DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                                        .addPreferredGap(RELATED)
                                                        .add(jButton2)
                                                        .addContainerGap())
                                                .add(layout.createSequentialGroup()
                                                        .add(jLabel1)
                                                        .add(228, 228, 228))
                                                .add(layout.createSequentialGroup()
                                                        .add(layout.createParallelGroup(LEADING)
                                                                .add(layout.createSequentialGroup()
                                                                        .add(29, 29, 29)
                                                                        .add(jScrollPane1, DEFAULT_SIZE, 492, Short.MAX_VALUE))
                                                                .add(jRadioButton1))
                                                        .addContainerGap())
                                                .add(layout.createSequentialGroup()
                                                        .add(jRadioButton2)
                                                        .addContainerGap(453, Short.MAX_VALUE)))
                                        .add(TRAILING, layout.createSequentialGroup()
                                                .add(jButton3)
                                                .addPreferredGap(RELATED)
                                                .add(jButton1)
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel1)
                                .addPreferredGap(RELATED)
                                .add(jRadioButton1)
                                .addPreferredGap(RELATED)
                                .add(jScrollPane1, DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addPreferredGap(RELATED)
                                .add(jRadioButton2)
                                .addPreferredGap(RELATED)
                                .add(layout.createParallelGroup(BASELINE)
                                        .add(jTextField1, PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE)
                                        .add(jButton2))
                                .addPreferredGap(RELATED)
                                .add(layout.createParallelGroup(BASELINE)
                                        .add(jButton1)
                                        .add(jButton3))
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JLabel jLabel1;
    private JList<Object> jList1;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JScrollPane jScrollPane1;
    private JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
